### ISSUE TITLE
Prepare V1

### ISSUE THREAD

**Issue by incepter** [incepter/react-async-states#46]
The following list must be resolved before talking about a v1.

- [x] add State.timestamp
- [x] Document `createSource`
- [x] Document `useRunAsyncState`
- [x] Document `state.timestamp`
- [x] Add FAQ and how to
- [x] Add tutorial section on the docs for onboarding.
- [x] Remove `props.aborted` in favor of `props.isAborted()` function.
- [x] Add `props.getState()` returning self state.
- [x] Rename `useRunAsyncState` -> `useRun` and `useASyncStateSelector` -> `useSelector`: #58 
- [x] Make the library react-18 strict mode friendly #64 
- [x] Add events #62 
- [x] Add dangerously run on creation #51 
- [x] Skip the pending state #56 
- [x] Code optimizations: #55
- [x] Add lanes support + docs + tests #70 
- [x] Add runSource, runSourceLane, runpSource, runpSourceLane global functions  + tests + docs #73 
- [x] Add `StateBoundary`
- [x] Change `resetStateOnDispose` default to `false` #79 
- [x] Support initialValue load from cache #80
- [x] Support `onCacheLoad` callback #80
- [x] Document `useSelector`
- [x] support `useSelector` outside provider via sources. #77 
- [x] Enhance folders and modules structure for better contributors onboarding
- [x] Make devtools extension: for each async state, create an shadow one connecting it to devtools. see #16 
- [x] add the tutorial section.
- [ ] Change logo and library visual identity #34 

**EDIT**
Given that Im the only one working on this, I ll deprioritize some things to be post v1.

POST V1:
- [ ] Add ts-example project
- [ ] Add github Actions for build jobs

The library for now may be a good release candidate. It has core features working good.

**Comment by incepter** [comment]
https://incepter.github.io/react-async-states/

**Comment by incepter** [comment]
Remove `props.aborted` in favor of `props.isAborted()` function.

People tend to desctructure a lot, and desctructuring a boolean may be a bad idea. should be replaced with is aborted function that needs to be executed and will return always an accurate result.

**Comment by incepter** [comment]
Producer may want to check the current state at any point of time (emit exists!), so getState should also exist

**Comment by incepter** [comment]
This PR can now be closed in peace

**Comment by incepter** [comment]
will continue in #87
